on:
  schedule:
    - cron: '*/30 * * * *'
  push:
    branches:
      - '*'
jobs:
  update-pots:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@master
        with:
          python-version: 3
      - run: git config --local user.email github-actions@github.com
      - run: git config --local user.name "GitHub Action's update-pots job"
      - run: ./update-pots.py 3.12
      - uses: ad-m/github-push-action@master
        if: ${GITHUB_REF_NAME} == "main"
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
